import { LoginPage } from "../../Pages/loginPage";
import { AddToCartPage } from "../../Pages/addToCartPage";
import { LogoutPage } from "../../Pages/logoutPage";

const logout = new LogoutPage(); 
const login = new LoginPage();
const cart = new AddToCartPage();

describe('Demoblaze Add To Cart Test', () => {
  let username, password;

  before(() => {
    cy.clearCookies();
    cy.clearLocalStorage();

    // Read user credentials from fixture (generated by signup test)
    cy.readFile('cypress/fixtures/userData.json').then((user) => {
      username = user.username;
      password = user.password;
    });

    // Navigate to base URL
    login.navigate(Cypress.env('baseUrl'));
  });

  it('should login using existing user', () => {
    // Reuse loginPage methods completely
    login.openLoginModal();
    login.login(username, password); 
    login.clickLoginBtn();
    login.verifyLogin(username);
  });

  it('should add product to cart', () => {
    // User is already logged in
    cart.clickLaptop();
    cart.addToCart();

    cy.on('window:alert', (alertText) => {
      expect(alertText).to.equal('Product added.');
    });
  });
  after(() => {
    logout.clickLogout(); // click logout and verify
  });
});
